### ISSUE TITLE
Unable to connect to Atlassian site

### ISSUE THREAD

**Issue by kevinbintoro** [atlassian/jira-cloud-for-sketch#12]
![screen shot 2017-11-21 at 4 19 23 pm](https://user-images.githubusercontent.com/33855235/33056120-cc1c1022-ced7-11e7-9ae8-aee44757267f.png)

Any idea why?

**Comment by kannonboy** [comment]
@kevinbintoro there's an incident effecting integrations for a small number of Jira Cloud sites at the moment. I'm looking into it with our SRE team at the moment, but I suspect analogfolk may be part of the effected group—I'll post back here once it's resolved.

**Comment by kannonboy** [comment]
@kevinbintoro I believe this issue has been resolved. Can you give it another try?

**Comment by kevinbintoro** [comment]
Still having issues. 

![screen shot 2017-11-22 at 9 06 06 am](https://user-images.githubusercontent.com/33855235/33099276-6fe01ac8-cf64-11e7-90bc-d0b191bf80c5.png)

**Comment by kannonboy** [comment]
Sorry to hear that @kevinbintoro. I'm able to connect to analogfolk.atlassian.net from my machine, so I might need to get you to send me your logs to help troubleshoot. The log is cleared automatically whenever Sketch is restarted, so you'll need to:

1. Reproduce the connection error.
2. Email the file at ~/Library/Logs/com.bohemiancoding.sketch3/Plugin Output.log to tim@atlassian.com

An easy way to get to this file is by opening Console.app (under Applications -> Utilities), navigating to Plugin Output.log, right-clicking and clicking "Reveal in Finder".

![31496473-349ddc34-afa7-11e7-8de2-a4d6118de3c8](https://user-images.githubusercontent.com/380545/33100648-3a974ba2-cf69-11e7-8081-76ddda31835c.png)

Thanks for your help!

**Comment by kannonboy** [comment]
Thanks for the logs @kevinbintoro!

It looks like some weird unicode characters were entered in your "Jira Cloud site" URL field, possibly  as the result of copying and pasting the URL from another document or web page.

Can you try deleting the contents of the "Jira Cloud site" URL field, and then typing by hand (not copying and pasting) `analogfolk.atlassian.net` and then clicking **Connect**.

**Comment by kevinbintoro** [comment]
@kannonboy this works! thanks for your help!
